### ISSUE TITLE
Degree/Year selection

### ISSUE THREAD

**Issue by diogotcorreia** [ist-bot-team/ist-discord-bot#51]
When a user joins the server, they should be prompted to select their degree as well as their enrollment year (e.g. 2020/2021).

To do this, use Discord's new selection components, which allows up to 25 items (should be enough). If it isn't due to the amount of degrees, separate undergraduate and master degrees.

Degrees that have both undergraduate and master, should be in the same option (e.g. L/MEIC-A).

Don't forget to add a "TurISTa" role and its selection ~~(should be given automatically when a user joins the server)~~ (see @D-Card 's comment below)

When a user selects an option, it should clear other degree roles they may have and then add the corresponding role. According to the degree, the user might also be given the "Alameda" or "Tagus Park" role. The same should happen for enrollment year (the year roles should be called something like "Ano 1 (2020/2021)").

In this initial development phase, keep configuration in a static JSON file. In the future, the course list/year list might be configured through slash commands, stored on SQLite and/or fetched from Fénix's API.

**Comment by D-Card** [comment]
Small note: the "TurISTa" role shouldn't be given automatically when a user joins the server since new users should only be able to see the "Inception" category channels before picking a role.

**Comment by RafDevX** [comment]
Implemented in #52
