### ISSUE TITLE
Temporary VC channels should just be threads of `#vc-chat`

### ISSUE THREAD

**Issue by RafDevX** [ist-bot-team/ist-discord-bot#55]
Bot user will probably need to join the thread.

**Comment by RafDevX** [comment]
@D-Card How should these be handled when everyone leaves the VC?

1. Set it so threads are automatically archived after 1hr (minimum possible) of inactivity;
2. Manually archive the thread;
3. Manually delete the thread;
4. Options 1 & 2; or
5. Options 1 & 3;

We probably want to retain the behavior where all history is lost when everyone leaves the channel, or shortly after.

**Comment by D-Card** [comment]
3

**Comment by RafDevX** [comment]
Implemented in #63
