### ISSUE TITLE
Add `degrees refresh-courses` command for all degrees

### ISSUE THREAD

**Issue by diogotcorreia** [ist-bot-team/ist-discord-bot#89]
https://github.com/ist-bot-team/ist-discord-bot/blob/2ba701cc64a29159c4eb2cdc89612ab31bee8295/src/modules/degrees.ts#L661

We might want to refresh all courses of all degrees, so making the `acronym` argument optional would help.
This happens when a semester changes so we need to update the RSS feed announcements URL for all courses of all degrees.

**Comment by RafDevX** [comment]
Fixed by #99
